### ISSUE TITLE
[BUG] v2.0.0 When clicking on StandType selector in MMExplorer

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaApp-React#456]
**Describe the bug**
Blank screen upon clicking on 

**To Reproduce**
1. Launch MMA
2. Click on 'Continue'
3. Select MMA Explorer
4. Click on "Stand Type"/"Inverted"
5. Error

**Expected behavior**

**Screenshots**
![image](https://github.com/WU-BIMAC/MicroMetaApp-React/assets/4050585/fcd6be2c-065f-4940-8d8d-d9d2e9d866be)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS Ventura 13.3.1
 - Version [e.g. 22] v2.0.0 b1

**ERROR**
microscopesBar.js:107 Uncaught TypeError: Cannot read properties of undefined (reading 'Schema_ID')
    at eval (microscopesBar.js:107:77)
    at Array.forEach (<anonymous>)
    at MicroscopesBar.filterMicroscopes (microscopesBar.js:98:45)
    at MicroscopesBar.eval (microscopesBar.js:182:20)
    at callCallback (/Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:12318:12)
    at commitUpdateQueue (/Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:12339:9)
    at commitLifeCycles (/Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:20709:11)
    at commitLayoutEffects (/Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:23426:7)
    at HTMLUnknownElement.callCallback (/Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (/Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:3994:16)
eval @ microscopesBar.js:107
filterMicroscopes @ microscopesBar.js:98
eval @ microscopesBar.js:182
callCallback @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:12318
commitUpdateQueue @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:12339
commitLifeCycles @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:20709
commitLayoutEffects @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:23426
callCallback @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:3945
invokeGuardedCallbackDev @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:3994
invokeGuardedCallback @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:4056
commitRootImpl @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:23151
unstable_runWithPriority @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/scheduler/cjs/scheduler.development.js:468
runWithPriority$1 @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11276
commitRoot @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22990
performSyncWorkOnRoot @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22329
(anonymous) @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11327
unstable_runWithPriority @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/scheduler/cjs/scheduler.development.js:468
runWithPriority$1 @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11276
flushSyncCallbackQueueImpl @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11322
flushSyncCallbackQueue @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11309
flushPendingDiscreteUpdates @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22372
flushDiscreteUpdates @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22353
finishEventHandler @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:3714
batchedEventUpdates @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:3748
dispatchEventForPluginEventSystem @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:8507
attemptToDispatchEvent @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:6005
dispatchEvent @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:5924
unstable_runWithPriority @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/scheduler/cjs/scheduler.development.js:468
runWithPriority$1 @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11276
discreteUpdates$1 @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22413
discreteUpdates @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:3756
dispatchDiscreteEvent @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:5889
Show 2 more frames
/Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:20085 The above error occurred in the <MicroscopesBar> component:

    at MicroscopesBar (webpack://MicroMetaAppElectron/./node_modules/micro-meta-explorer/es/components/microscopesBar.js?:40:5)
    at div
    at div
    at MicroMetaExplorerContainer (webpack://MicroMetaAppElectron/./node_modules/micro-meta-explorer/es/app.js?:907:5)
    at MicroMetaExplorer (webpack://MicroMetaAppElectron/./node_modules/micro-meta-explorer/es/app.js?:48:5)
    at div
    at MicroMetaAppElectronComponent (webpack://MicroMetaAppElectron/./src/app.js?:349:5)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:20085
update.callback @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:20118
callCallback @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:12318
commitUpdateQueue @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:12339
commitLifeCycles @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:20736
commitLayoutEffects @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:23426
callCallback @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:3945
invokeGuardedCallbackDev @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:3994
invokeGuardedCallback @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:4056
commitRootImpl @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:23151
unstable_runWithPriority @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/scheduler/cjs/scheduler.development.js:468
runWithPriority$1 @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11276
commitRoot @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22990
performSyncWorkOnRoot @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22329
(anonymous) @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11327
unstable_runWithPriority @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/scheduler/cjs/scheduler.development.js:468
runWithPriority$1 @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11276
flushSyncCallbackQueueImpl @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11322
flushSyncCallbackQueue @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11309
flushPendingDiscreteUpdates @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22372
flushDiscreteUpdates @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22353
finishEventHandler @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:3714
batchedEventUpdates @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:3748
dispatchEventForPluginEventSystem @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:8507
attemptToDispatchEvent @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:6005
dispatchEvent @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:5924
unstable_runWithPriority @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/scheduler/cjs/scheduler.development.js:468
runWithPriority$1 @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11276
discreteUpdates$1 @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22413
discreteUpdates @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:3756
dispatchDiscreteEvent @ /Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:5889
/Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11340 Uncaught TypeError: Cannot read properties of undefined (reading 'Schema_ID')
    at eval (microscopesBar.js:107:77)
    at Array.forEach (<anonymous>)
    at MicroscopesBar.filterMicroscopes (microscopesBar.js:98:45)
    at MicroscopesBar.eval (microscopesBar.js:182:20)
    at callCallback (/Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:12318:12)
    at commitUpdateQueue (/Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:12339:9)
    at commitLifeCycles (/Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:20709:11)
    at commitLayoutEffects (/Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:23426:7)
    at HTMLUnknownElement.callCallback (/Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (/Users/strambc/Dropbox/Workstuff/4DN_Dropbox/2018-4DN_metadata standard + software_model development/4DN-OME_Micro-Meta-App_devel/Micro-Meta App Software/react_beta_releases/current stable release/2.0.0-b1/2.0.0-b1_micro-meta-app-electron.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:3994:16)

**Comment by strambc** [comment]
Same error with all other options in the selector

![image](https://github.com/WU-BIMAC/MicroMetaApp-React/assets/4050585/e5733214-5e14-4a7c-92bf-97671e242102)
